<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>predictive risk</name>
  <uuid>c2b1941e-0569-475b-8f57-b93f044b10d3</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the machine learning scoreboard computed from
	Client Information being Client ,
	Industry being Industry ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
